# Generated by Django 4.1.3 on 2022-12-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalpolicy2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iagreetopolicytracker',
            name='i_agreed_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='iagreetopolicytracker',
            name='legal_policy_type',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='iagreetopolicytracker',
            name='session_id',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
