# Generated by Django 4.1.2 on 2023-02-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalpolicy2', '0002_iagreetopolicytracker_i_agreed_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iagreetopolicytracker',
            name='user_id',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='iagreetopolicytracker',
            name='username',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
